name: CI


on:
  push:
    branches:
      - master
      - "!dependabot/**"
  pull_request:
  workflow_dispatch:


permissions:
  contents: read


jobs:
  test:
    name: Python ${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}


    strategy:
      fail-fast: false
      matrix:
        python:
          - '3.12'
        os:
          - ubuntu-latest


    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip


      - name: Print versions
        run: |
          python --version
          pip --version


      - name: Install Python dependencies
        run: pip install -r requirements.txt


      - name: Run lint
        run: flake8


      - name: Run tests
        run: python updateHostsFile.py --auto


- name: Commit changes
        run: |
          git add .
          git commit -m "Update hosts file" || echo "No changes to commit"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Push changes
        run: |
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          git add .
          git commit -m "Update hosts
